### ISSUE TITLE
README.me links to Bosnian official developer docs

### ISSUE THREAD

**Issue by Teekivi** [abiosoft/hello-elementary#1]
The URL for "official docs" link in README.md directs the link follower to the Bosnian-language variant of the developer docs. The docs themselves are not translated, and thus are displayed in English. However, the navigation bar is among the parts of the site that are translated.

I think it would be desirable to make the link direct to the English documentation site.
Current URL: https://elementary.io/bs/docs/code/getting-started
Proposed URL: https://elementary.io/en/docs/code/getting-started

**Comment by abiosoft** [comment]
Must've been a mistake from me. Thanks for spotting it.
